spring:
  application:
    name: carrim-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carrim}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    default-schema: carrim
    schemas: carrim
    clean-disabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: carrim
server:
  port: 8082
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
